
trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
  - bash: |
      git diff --name-only origin/master  > tmp.txt
    displayName: Git diff
  
  - task: DotNetCoreCLI@2
    displayName: Run RequirementsClient
    inputs:
      command: run
      projects: requirementsClient\requirementsClient.csproj
      arguments: $(System.AccessToken)